# Generated by Django 3.1.1 on 2020-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_count_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='vis_month',
            field=models.IntegerField(default=0),
        ),
    ]
