# Generated by Django 3.1.1 on 2021-03-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_count_vis_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='vis_day',
        ),
    ]
